/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAuthRouteRouteImport } from './routes/(public)/_auth/route'
import { Route as privateDashboardRouteRouteImport } from './routes/(private)/_dashboard/route'
import { Route as publicAuthSignUpIndexRouteImport } from './routes/(public)/_auth/sign-up/index'
import { Route as publicAuthSignInIndexRouteImport } from './routes/(public)/_auth/sign-in/index'
import { Route as privateDashboardSubjectsIndexRouteImport } from './routes/(private)/_dashboard/subjects/index'
import { Route as privateDashboardSettingsIndexRouteImport } from './routes/(private)/_dashboard/settings/index'
import { Route as privateDashboardSchedulerIndexRouteImport } from './routes/(private)/_dashboard/scheduler/index'
import { Route as privateDashboardRevisionPlannerIndexRouteImport } from './routes/(private)/_dashboard/revision-planner/index'
import { Route as privateDashboardPerformanceIndexRouteImport } from './routes/(private)/_dashboard/performance/index'
import { Route as privateDashboardDashboardIndexRouteImport } from './routes/(private)/_dashboard/dashboard/index'

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthRouteRoute = publicAuthRouteRouteImport.update({
  id: '/(public)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const privateDashboardRouteRoute = privateDashboardRouteRouteImport.update({
  id: '/(private)/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthSignUpIndexRoute = publicAuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => publicAuthRouteRoute,
} as any)
const publicAuthSignInIndexRoute = publicAuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => publicAuthRouteRoute,
} as any)
const privateDashboardSubjectsIndexRoute =
  privateDashboardSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardSettingsIndexRoute =
  privateDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardSchedulerIndexRoute =
  privateDashboardSchedulerIndexRouteImport.update({
    id: '/scheduler/',
    path: '/scheduler/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardRevisionPlannerIndexRoute =
  privateDashboardRevisionPlannerIndexRouteImport.update({
    id: '/revision-planner/',
    path: '/revision-planner/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardPerformanceIndexRoute =
  privateDashboardPerformanceIndexRouteImport.update({
    id: '/performance/',
    path: '/performance/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardDashboardIndexRoute =
  privateDashboardDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/dashboard/': typeof privateDashboardDashboardIndexRoute
  '/performance/': typeof privateDashboardPerformanceIndexRoute
  '/revision-planner/': typeof privateDashboardRevisionPlannerIndexRoute
  '/scheduler/': typeof privateDashboardSchedulerIndexRoute
  '/settings/': typeof privateDashboardSettingsIndexRoute
  '/subjects/': typeof privateDashboardSubjectsIndexRoute
  '/sign-in/': typeof publicAuthSignInIndexRoute
  '/sign-up/': typeof publicAuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/dashboard': typeof privateDashboardDashboardIndexRoute
  '/performance': typeof privateDashboardPerformanceIndexRoute
  '/revision-planner': typeof privateDashboardRevisionPlannerIndexRoute
  '/scheduler': typeof privateDashboardSchedulerIndexRoute
  '/settings': typeof privateDashboardSettingsIndexRoute
  '/subjects': typeof privateDashboardSubjectsIndexRoute
  '/sign-in': typeof publicAuthSignInIndexRoute
  '/sign-up': typeof publicAuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)/_dashboard': typeof privateDashboardRouteRouteWithChildren
  '/(public)/_auth': typeof publicAuthRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(private)/_dashboard/dashboard/': typeof privateDashboardDashboardIndexRoute
  '/(private)/_dashboard/performance/': typeof privateDashboardPerformanceIndexRoute
  '/(private)/_dashboard/revision-planner/': typeof privateDashboardRevisionPlannerIndexRoute
  '/(private)/_dashboard/scheduler/': typeof privateDashboardSchedulerIndexRoute
  '/(private)/_dashboard/settings/': typeof privateDashboardSettingsIndexRoute
  '/(private)/_dashboard/subjects/': typeof privateDashboardSubjectsIndexRoute
  '/(public)/_auth/sign-in/': typeof publicAuthSignInIndexRoute
  '/(public)/_auth/sign-up/': typeof publicAuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/performance/'
    | '/revision-planner/'
    | '/scheduler/'
    | '/settings/'
    | '/subjects/'
    | '/sign-in/'
    | '/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/performance'
    | '/revision-planner'
    | '/scheduler'
    | '/settings'
    | '/subjects'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/(private)/_dashboard'
    | '/(public)/_auth'
    | '/(public)/'
    | '/(private)/_dashboard/dashboard/'
    | '/(private)/_dashboard/performance/'
    | '/(private)/_dashboard/revision-planner/'
    | '/(private)/_dashboard/scheduler/'
    | '/(private)/_dashboard/settings/'
    | '/(private)/_dashboard/subjects/'
    | '/(public)/_auth/sign-in/'
    | '/(public)/_auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateDashboardRouteRoute: typeof privateDashboardRouteRouteWithChildren
  publicAuthRouteRoute: typeof publicAuthRouteRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_auth': {
      id: '/(public)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_dashboard': {
      id: '/(private)/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_auth/sign-up/': {
      id: '/(public)/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof publicAuthSignUpIndexRouteImport
      parentRoute: typeof publicAuthRouteRoute
    }
    '/(public)/_auth/sign-in/': {
      id: '/(public)/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof publicAuthSignInIndexRouteImport
      parentRoute: typeof publicAuthRouteRoute
    }
    '/(private)/_dashboard/subjects/': {
      id: '/(private)/_dashboard/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof privateDashboardSubjectsIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/settings/': {
      id: '/(private)/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof privateDashboardSettingsIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/scheduler/': {
      id: '/(private)/_dashboard/scheduler/'
      path: '/scheduler'
      fullPath: '/scheduler/'
      preLoaderRoute: typeof privateDashboardSchedulerIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/revision-planner/': {
      id: '/(private)/_dashboard/revision-planner/'
      path: '/revision-planner'
      fullPath: '/revision-planner/'
      preLoaderRoute: typeof privateDashboardRevisionPlannerIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/performance/': {
      id: '/(private)/_dashboard/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof privateDashboardPerformanceIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/dashboard/': {
      id: '/(private)/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof privateDashboardDashboardIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
  }
}

interface privateDashboardRouteRouteChildren {
  privateDashboardDashboardIndexRoute: typeof privateDashboardDashboardIndexRoute
  privateDashboardPerformanceIndexRoute: typeof privateDashboardPerformanceIndexRoute
  privateDashboardRevisionPlannerIndexRoute: typeof privateDashboardRevisionPlannerIndexRoute
  privateDashboardSchedulerIndexRoute: typeof privateDashboardSchedulerIndexRoute
  privateDashboardSettingsIndexRoute: typeof privateDashboardSettingsIndexRoute
  privateDashboardSubjectsIndexRoute: typeof privateDashboardSubjectsIndexRoute
}

const privateDashboardRouteRouteChildren: privateDashboardRouteRouteChildren = {
  privateDashboardDashboardIndexRoute: privateDashboardDashboardIndexRoute,
  privateDashboardPerformanceIndexRoute: privateDashboardPerformanceIndexRoute,
  privateDashboardRevisionPlannerIndexRoute:
    privateDashboardRevisionPlannerIndexRoute,
  privateDashboardSchedulerIndexRoute: privateDashboardSchedulerIndexRoute,
  privateDashboardSettingsIndexRoute: privateDashboardSettingsIndexRoute,
  privateDashboardSubjectsIndexRoute: privateDashboardSubjectsIndexRoute,
}

const privateDashboardRouteRouteWithChildren =
  privateDashboardRouteRoute._addFileChildren(
    privateDashboardRouteRouteChildren,
  )

interface publicAuthRouteRouteChildren {
  publicAuthSignInIndexRoute: typeof publicAuthSignInIndexRoute
  publicAuthSignUpIndexRoute: typeof publicAuthSignUpIndexRoute
}

const publicAuthRouteRouteChildren: publicAuthRouteRouteChildren = {
  publicAuthSignInIndexRoute: publicAuthSignInIndexRoute,
  publicAuthSignUpIndexRoute: publicAuthSignUpIndexRoute,
}

const publicAuthRouteRouteWithChildren = publicAuthRouteRoute._addFileChildren(
  publicAuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateDashboardRouteRoute: privateDashboardRouteRouteWithChildren,
  publicAuthRouteRoute: publicAuthRouteRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
