/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateDashboardRouteRouteImport } from './routes/(private)/_dashboard/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAuthRouteRouteImport } from './routes/(public)/_auth/route'
import { Route as publicOnboardingIndexRouteImport } from './routes/(public)/onboarding/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as privateDashboardAnalyticsIndexRouteImport } from './routes/(private)/_dashboard/analytics/index'
import { Route as privateDashboardCalendarIndexRouteImport } from './routes/(private)/_dashboard/calendar/index'
import { Route as privateDashboardDashboardIndexRouteImport } from './routes/(private)/_dashboard/dashboard/index'
import { Route as privateDashboardExamsIndexRouteImport } from './routes/(private)/_dashboard/exams/index'
import { Route as privateDashboardGoalsIndexRouteImport } from './routes/(private)/_dashboard/goals/index'
import { Route as privateDashboardPerformanceIndexRouteImport } from './routes/(private)/_dashboard/performance/index'
import { Route as privateDashboardPlansIndexRouteImport } from './routes/(private)/_dashboard/plans/index'
import { Route as privateDashboardPomodoroIndexRouteImport } from './routes/(private)/_dashboard/pomodoro/index'
import { Route as privateDashboardProfileIndexRouteImport } from './routes/(private)/_dashboard/profile/index'
import { Route as privateDashboardRevisionPlannerIndexRouteImport } from './routes/(private)/_dashboard/revision-planner/index'
import { Route as privateDashboardSchedulerIndexRouteImport } from './routes/(private)/_dashboard/scheduler/index'
import { Route as privateDashboardSessionsIndexRouteImport } from './routes/(private)/_dashboard/sessions/index'
import { Route as privateDashboardSettingsIndexRouteImport } from './routes/(private)/_dashboard/settings/index'
import { Route as privateDashboardSubjectsIndexRouteImport } from './routes/(private)/_dashboard/subjects/index'
import { Route as privateDashboardTasksIndexRouteImport } from './routes/(private)/_dashboard/tasks/index'
import { Route as publicAuthForgotPasswordIndexRouteImport } from './routes/(public)/_auth/forgot-password/index'
import { Route as publicAuthResetPasswordIndexRouteImport } from './routes/(public)/_auth/reset-password/index'
import { Route as publicAuthSignInIndexRouteImport } from './routes/(public)/_auth/sign-in/index'
import { Route as publicAuthSignUpIndexRouteImport } from './routes/(public)/_auth/sign-up/index'

const privateDashboardRouteRoute = privateDashboardRouteRouteImport.update({
  id: '/(private)/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthRouteRoute = publicAuthRouteRouteImport.update({
  id: '/(public)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const publicOnboardingIndexRoute = publicOnboardingIndexRouteImport.update({
  id: '/(public)/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const privateDashboardAnalyticsIndexRoute =
  privateDashboardAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardCalendarIndexRoute =
  privateDashboardCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardDashboardIndexRoute =
  privateDashboardDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardExamsIndexRoute =
  privateDashboardExamsIndexRouteImport.update({
    id: '/exams/',
    path: '/exams/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardGoalsIndexRoute =
  privateDashboardGoalsIndexRouteImport.update({
    id: '/goals/',
    path: '/goals/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardPerformanceIndexRoute =
  privateDashboardPerformanceIndexRouteImport.update({
    id: '/performance/',
    path: '/performance/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardPlansIndexRoute =
  privateDashboardPlansIndexRouteImport.update({
    id: '/plans/',
    path: '/plans/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardPomodoroIndexRoute =
  privateDashboardPomodoroIndexRouteImport.update({
    id: '/pomodoro/',
    path: '/pomodoro/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardProfileIndexRoute =
  privateDashboardProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardRevisionPlannerIndexRoute =
  privateDashboardRevisionPlannerIndexRouteImport.update({
    id: '/revision-planner/',
    path: '/revision-planner/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardSchedulerIndexRoute =
  privateDashboardSchedulerIndexRouteImport.update({
    id: '/scheduler/',
    path: '/scheduler/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardSessionsIndexRoute =
  privateDashboardSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardSettingsIndexRoute =
  privateDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardSubjectsIndexRoute =
  privateDashboardSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardTasksIndexRoute =
  privateDashboardTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const publicAuthForgotPasswordIndexRoute =
  publicAuthForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => publicAuthRouteRoute,
  } as any)
const publicAuthResetPasswordIndexRoute =
  publicAuthResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => publicAuthRouteRoute,
  } as any)
const publicAuthSignInIndexRoute = publicAuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => publicAuthRouteRoute,
} as any)
const publicAuthSignUpIndexRoute = publicAuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => publicAuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/onboarding/': typeof publicOnboardingIndexRoute
  '/analytics/': typeof privateDashboardAnalyticsIndexRoute
  '/calendar/': typeof privateDashboardCalendarIndexRoute
  '/dashboard/': typeof privateDashboardDashboardIndexRoute
  '/exams/': typeof privateDashboardExamsIndexRoute
  '/goals/': typeof privateDashboardGoalsIndexRoute
  '/performance/': typeof privateDashboardPerformanceIndexRoute
  '/plans/': typeof privateDashboardPlansIndexRoute
  '/pomodoro/': typeof privateDashboardPomodoroIndexRoute
  '/profile/': typeof privateDashboardProfileIndexRoute
  '/revision-planner/': typeof privateDashboardRevisionPlannerIndexRoute
  '/scheduler/': typeof privateDashboardSchedulerIndexRoute
  '/sessions/': typeof privateDashboardSessionsIndexRoute
  '/settings/': typeof privateDashboardSettingsIndexRoute
  '/subjects/': typeof privateDashboardSubjectsIndexRoute
  '/tasks/': typeof privateDashboardTasksIndexRoute
  '/forgot-password/': typeof publicAuthForgotPasswordIndexRoute
  '/reset-password/': typeof publicAuthResetPasswordIndexRoute
  '/sign-in/': typeof publicAuthSignInIndexRoute
  '/sign-up/': typeof publicAuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/onboarding': typeof publicOnboardingIndexRoute
  '/analytics': typeof privateDashboardAnalyticsIndexRoute
  '/calendar': typeof privateDashboardCalendarIndexRoute
  '/dashboard': typeof privateDashboardDashboardIndexRoute
  '/exams': typeof privateDashboardExamsIndexRoute
  '/goals': typeof privateDashboardGoalsIndexRoute
  '/performance': typeof privateDashboardPerformanceIndexRoute
  '/plans': typeof privateDashboardPlansIndexRoute
  '/pomodoro': typeof privateDashboardPomodoroIndexRoute
  '/profile': typeof privateDashboardProfileIndexRoute
  '/revision-planner': typeof privateDashboardRevisionPlannerIndexRoute
  '/scheduler': typeof privateDashboardSchedulerIndexRoute
  '/sessions': typeof privateDashboardSessionsIndexRoute
  '/settings': typeof privateDashboardSettingsIndexRoute
  '/subjects': typeof privateDashboardSubjectsIndexRoute
  '/tasks': typeof privateDashboardTasksIndexRoute
  '/forgot-password': typeof publicAuthForgotPasswordIndexRoute
  '/reset-password': typeof publicAuthResetPasswordIndexRoute
  '/sign-in': typeof publicAuthSignInIndexRoute
  '/sign-up': typeof publicAuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)/_dashboard': typeof privateDashboardRouteRouteWithChildren
  '/(public)/_auth': typeof publicAuthRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(public)/onboarding/': typeof publicOnboardingIndexRoute
  '/(private)/_dashboard/analytics/': typeof privateDashboardAnalyticsIndexRoute
  '/(private)/_dashboard/calendar/': typeof privateDashboardCalendarIndexRoute
  '/(private)/_dashboard/dashboard/': typeof privateDashboardDashboardIndexRoute
  '/(private)/_dashboard/exams/': typeof privateDashboardExamsIndexRoute
  '/(private)/_dashboard/goals/': typeof privateDashboardGoalsIndexRoute
  '/(private)/_dashboard/performance/': typeof privateDashboardPerformanceIndexRoute
  '/(private)/_dashboard/plans/': typeof privateDashboardPlansIndexRoute
  '/(private)/_dashboard/pomodoro/': typeof privateDashboardPomodoroIndexRoute
  '/(private)/_dashboard/profile/': typeof privateDashboardProfileIndexRoute
  '/(private)/_dashboard/revision-planner/': typeof privateDashboardRevisionPlannerIndexRoute
  '/(private)/_dashboard/scheduler/': typeof privateDashboardSchedulerIndexRoute
  '/(private)/_dashboard/sessions/': typeof privateDashboardSessionsIndexRoute
  '/(private)/_dashboard/settings/': typeof privateDashboardSettingsIndexRoute
  '/(private)/_dashboard/subjects/': typeof privateDashboardSubjectsIndexRoute
  '/(private)/_dashboard/tasks/': typeof privateDashboardTasksIndexRoute
  '/(public)/_auth/forgot-password/': typeof publicAuthForgotPasswordIndexRoute
  '/(public)/_auth/reset-password/': typeof publicAuthResetPasswordIndexRoute
  '/(public)/_auth/sign-in/': typeof publicAuthSignInIndexRoute
  '/(public)/_auth/sign-up/': typeof publicAuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/onboarding/'
    | '/analytics/'
    | '/calendar/'
    | '/dashboard/'
    | '/exams/'
    | '/goals/'
    | '/performance/'
    | '/plans/'
    | '/pomodoro/'
    | '/profile/'
    | '/revision-planner/'
    | '/scheduler/'
    | '/sessions/'
    | '/settings/'
    | '/subjects/'
    | '/tasks/'
    | '/forgot-password/'
    | '/reset-password/'
    | '/sign-in/'
    | '/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/onboarding'
    | '/analytics'
    | '/calendar'
    | '/dashboard'
    | '/exams'
    | '/goals'
    | '/performance'
    | '/plans'
    | '/pomodoro'
    | '/profile'
    | '/revision-planner'
    | '/scheduler'
    | '/sessions'
    | '/settings'
    | '/subjects'
    | '/tasks'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/(private)/_dashboard'
    | '/(public)/_auth'
    | '/(public)/'
    | '/api/auth/$'
    | '/(public)/onboarding/'
    | '/(private)/_dashboard/analytics/'
    | '/(private)/_dashboard/calendar/'
    | '/(private)/_dashboard/dashboard/'
    | '/(private)/_dashboard/exams/'
    | '/(private)/_dashboard/goals/'
    | '/(private)/_dashboard/performance/'
    | '/(private)/_dashboard/plans/'
    | '/(private)/_dashboard/pomodoro/'
    | '/(private)/_dashboard/profile/'
    | '/(private)/_dashboard/revision-planner/'
    | '/(private)/_dashboard/scheduler/'
    | '/(private)/_dashboard/sessions/'
    | '/(private)/_dashboard/settings/'
    | '/(private)/_dashboard/subjects/'
    | '/(private)/_dashboard/tasks/'
    | '/(public)/_auth/forgot-password/'
    | '/(public)/_auth/reset-password/'
    | '/(public)/_auth/sign-in/'
    | '/(public)/_auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateDashboardRouteRoute: typeof privateDashboardRouteRouteWithChildren
  publicAuthRouteRoute: typeof publicAuthRouteRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  publicOnboardingIndexRoute: typeof publicOnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)/_dashboard': {
      id: '/(private)/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_auth': {
      id: '/(public)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/onboarding/': {
      id: '/(public)/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof publicOnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_dashboard/analytics/': {
      id: '/(private)/_dashboard/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof privateDashboardAnalyticsIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/calendar/': {
      id: '/(private)/_dashboard/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof privateDashboardCalendarIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/dashboard/': {
      id: '/(private)/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof privateDashboardDashboardIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/exams/': {
      id: '/(private)/_dashboard/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof privateDashboardExamsIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/goals/': {
      id: '/(private)/_dashboard/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof privateDashboardGoalsIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/performance/': {
      id: '/(private)/_dashboard/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof privateDashboardPerformanceIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/plans/': {
      id: '/(private)/_dashboard/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof privateDashboardPlansIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/pomodoro/': {
      id: '/(private)/_dashboard/pomodoro/'
      path: '/pomodoro'
      fullPath: '/pomodoro/'
      preLoaderRoute: typeof privateDashboardPomodoroIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/profile/': {
      id: '/(private)/_dashboard/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof privateDashboardProfileIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/revision-planner/': {
      id: '/(private)/_dashboard/revision-planner/'
      path: '/revision-planner'
      fullPath: '/revision-planner/'
      preLoaderRoute: typeof privateDashboardRevisionPlannerIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/scheduler/': {
      id: '/(private)/_dashboard/scheduler/'
      path: '/scheduler'
      fullPath: '/scheduler/'
      preLoaderRoute: typeof privateDashboardSchedulerIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/sessions/': {
      id: '/(private)/_dashboard/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof privateDashboardSessionsIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/settings/': {
      id: '/(private)/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof privateDashboardSettingsIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/subjects/': {
      id: '/(private)/_dashboard/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof privateDashboardSubjectsIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/tasks/': {
      id: '/(private)/_dashboard/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof privateDashboardTasksIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(public)/_auth/forgot-password/': {
      id: '/(public)/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof publicAuthForgotPasswordIndexRouteImport
      parentRoute: typeof publicAuthRouteRoute
    }
    '/(public)/_auth/reset-password/': {
      id: '/(public)/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof publicAuthResetPasswordIndexRouteImport
      parentRoute: typeof publicAuthRouteRoute
    }
    '/(public)/_auth/sign-in/': {
      id: '/(public)/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof publicAuthSignInIndexRouteImport
      parentRoute: typeof publicAuthRouteRoute
    }
    '/(public)/_auth/sign-up/': {
      id: '/(public)/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof publicAuthSignUpIndexRouteImport
      parentRoute: typeof publicAuthRouteRoute
    }
  }
}

interface privateDashboardRouteRouteChildren {
  privateDashboardAnalyticsIndexRoute: typeof privateDashboardAnalyticsIndexRoute
  privateDashboardCalendarIndexRoute: typeof privateDashboardCalendarIndexRoute
  privateDashboardDashboardIndexRoute: typeof privateDashboardDashboardIndexRoute
  privateDashboardExamsIndexRoute: typeof privateDashboardExamsIndexRoute
  privateDashboardGoalsIndexRoute: typeof privateDashboardGoalsIndexRoute
  privateDashboardPerformanceIndexRoute: typeof privateDashboardPerformanceIndexRoute
  privateDashboardPlansIndexRoute: typeof privateDashboardPlansIndexRoute
  privateDashboardPomodoroIndexRoute: typeof privateDashboardPomodoroIndexRoute
  privateDashboardProfileIndexRoute: typeof privateDashboardProfileIndexRoute
  privateDashboardRevisionPlannerIndexRoute: typeof privateDashboardRevisionPlannerIndexRoute
  privateDashboardSchedulerIndexRoute: typeof privateDashboardSchedulerIndexRoute
  privateDashboardSessionsIndexRoute: typeof privateDashboardSessionsIndexRoute
  privateDashboardSettingsIndexRoute: typeof privateDashboardSettingsIndexRoute
  privateDashboardSubjectsIndexRoute: typeof privateDashboardSubjectsIndexRoute
  privateDashboardTasksIndexRoute: typeof privateDashboardTasksIndexRoute
}

const privateDashboardRouteRouteChildren: privateDashboardRouteRouteChildren = {
  privateDashboardAnalyticsIndexRoute: privateDashboardAnalyticsIndexRoute,
  privateDashboardCalendarIndexRoute: privateDashboardCalendarIndexRoute,
  privateDashboardDashboardIndexRoute: privateDashboardDashboardIndexRoute,
  privateDashboardExamsIndexRoute: privateDashboardExamsIndexRoute,
  privateDashboardGoalsIndexRoute: privateDashboardGoalsIndexRoute,
  privateDashboardPerformanceIndexRoute: privateDashboardPerformanceIndexRoute,
  privateDashboardPlansIndexRoute: privateDashboardPlansIndexRoute,
  privateDashboardPomodoroIndexRoute: privateDashboardPomodoroIndexRoute,
  privateDashboardProfileIndexRoute: privateDashboardProfileIndexRoute,
  privateDashboardRevisionPlannerIndexRoute:
    privateDashboardRevisionPlannerIndexRoute,
  privateDashboardSchedulerIndexRoute: privateDashboardSchedulerIndexRoute,
  privateDashboardSessionsIndexRoute: privateDashboardSessionsIndexRoute,
  privateDashboardSettingsIndexRoute: privateDashboardSettingsIndexRoute,
  privateDashboardSubjectsIndexRoute: privateDashboardSubjectsIndexRoute,
  privateDashboardTasksIndexRoute: privateDashboardTasksIndexRoute,
}

const privateDashboardRouteRouteWithChildren =
  privateDashboardRouteRoute._addFileChildren(
    privateDashboardRouteRouteChildren,
  )

interface publicAuthRouteRouteChildren {
  publicAuthForgotPasswordIndexRoute: typeof publicAuthForgotPasswordIndexRoute
  publicAuthResetPasswordIndexRoute: typeof publicAuthResetPasswordIndexRoute
  publicAuthSignInIndexRoute: typeof publicAuthSignInIndexRoute
  publicAuthSignUpIndexRoute: typeof publicAuthSignUpIndexRoute
}

const publicAuthRouteRouteChildren: publicAuthRouteRouteChildren = {
  publicAuthForgotPasswordIndexRoute: publicAuthForgotPasswordIndexRoute,
  publicAuthResetPasswordIndexRoute: publicAuthResetPasswordIndexRoute,
  publicAuthSignInIndexRoute: publicAuthSignInIndexRoute,
  publicAuthSignUpIndexRoute: publicAuthSignUpIndexRoute,
}

const publicAuthRouteRouteWithChildren = publicAuthRouteRoute._addFileChildren(
  publicAuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateDashboardRouteRoute: privateDashboardRouteRouteWithChildren,
  publicAuthRouteRoute: publicAuthRouteRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  publicOnboardingIndexRoute: publicOnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
