import { createFileRoute, useRouter } from "@tanstack/react-router";
import { CalendarClock, Check, Clock3, Sparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Badge } from "#/components/ui/badge";
import { Button } from "#/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "#/components/ui/card";
import { Input } from "#/components/ui/input";
import { getPlans } from "#/features/plans/server/plans";
import {
	createSession,
	getSessions,
} from "#/features/sessions/server/sessions";

export const Route = createFileRoute("/(private)/_dashboard/revision-planner/")(
	{
		loader: async () => ({
			plans: await getPlans(),
			sessions: await getSessions(),
		}),
		component: RevisionPlannerPage,
	},
);

function RevisionPlannerPage() {
	const { plans, sessions } = Route.useLoaderData();
	const router = useRouter();
	const [planId, setPlanId] = useState(
		plans.find((plan) => plan.status === "ACTIVE")?.id ?? "",
	);
	const [hours, setHours] = useState(10);
	const [saving, setSaving] = useState(false);
	const activePlan = plans.find((plan) => plan.id === planId);
	const generatedSessions = sessions.filter(
		(session) =>
			session.planId === planId &&
			new Date(session.scheduledDate) >= new Date(),
	).length;
	async function generatePlan() {
		if (!activePlan || activePlan.subjects.length === 0) {
			toast.error("Select a plan with subjects first");
			return;
		}
		setSaving(true);
		try {
			const minutes = Math.max(
				15,
				Math.round((hours * 60) / activePlan.subjects.length),
			);
			await Promise.all(
				activePlan.subjects.map(({ subject }, index) => {
					const date = new Date();
					date.setDate(date.getDate() + index + 1);
					date.setHours(18, 0, 0, 0);
					return createSession({
						data: {
							title: `Revision: ${subject.name}`,
							subjectId: subject.id,
							planId: activePlan.id,
							scheduledDate: date,
							durationMin: minutes,
							notes: "Generated by Revision Planner",
						},
					});
				}),
			);
			await router.invalidate();
			toast.success("Revision sessions generated");
		} catch (error) {
			toast.error(
				error instanceof Error
					? error.message
					: "Unable to generate revision plan",
			);
		} finally {
			setSaving(false);
		}
	}
	return (
		<div className="w-full space-y-5">
			<section className="border-b border-border pb-5">
				<p className="text-xs font-semibold uppercase tracking-[0.12em] text-primary">
					Revision Planner
				</p>
				<h1 className="mt-1 text-2xl font-bold tracking-tight">
					Turn plans into revision sessions
				</h1>
				<p className="mt-1 text-sm text-muted-foreground">
					Distribute your available study time across every subject in an active
					plan.
				</p>
			</section>
			<div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]">
				<Card className="rounded-xl border bg-card py-0 shadow-sm">
					<CardHeader className="px-5 pb-2 pt-5">
						<CardTitle className="flex items-center gap-2 text-sm">
							<Sparkles className="size-4 text-primary" /> Generate a revision
							week
						</CardTitle>
					</CardHeader>
					<CardContent className="space-y-5 p-5">
						<label className="block space-y-1 text-sm">
							<span className="font-medium">Active study plan</span>
							<select
								value={planId}
								onChange={(event) => setPlanId(event.target.value)}
								className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"
							>
								<option value="">Select a plan</option>
								{plans
									.filter((plan) => plan.status === "ACTIVE")
									.map((plan) => (
										<option key={plan.id} value={plan.id}>
											{plan.title}
										</option>
									))}
							</select>
						</label>
						<label className="block space-y-1 text-sm">
							<span className="font-medium">Hours available this week</span>
							<Input
								type="number"
								min="1"
								max="168"
								value={hours}
								onChange={(event) => setHours(Number(event.target.value))}
							/>
						</label>
						<div className="rounded-lg bg-muted/60 p-4 text-sm">
							<p className="font-medium">Subjects included</p>
							<div className="mt-3 flex flex-wrap gap-2">
								{activePlan?.subjects.map(({ subject }) => (
									<Badge key={subject.id} variant="secondary">
										{subject.name}
									</Badge>
								)) ?? (
									<span className="text-xs text-muted-foreground">
										Choose an active plan.
									</span>
								)}
							</div>
						</div>
						<Button onClick={generatePlan} disabled={saving || !activePlan}>
							<CalendarClock />
							{saving ? "Generating..." : "Generate revision sessions"}
						</Button>
					</CardContent>
				</Card>
				<div className="space-y-5">
					<Card className="rounded-xl border bg-primary text-primary-foreground py-0 shadow-sm">
						<CardContent className="p-5">
							<Clock3 className="size-5" />
							<p className="mt-4 text-xs uppercase tracking-widest text-primary-foreground/70">
								Upcoming generated sessions
							</p>
							<p className="mt-1 text-2xl font-bold">{generatedSessions}</p>
							<p className="mt-1 text-xs text-primary-foreground/75">
								For the selected study plan
							</p>
						</CardContent>
					</Card>
					<Card className="rounded-xl border bg-card py-0 shadow-sm">
						<CardHeader className="px-5 pb-2 pt-5">
							<CardTitle className="text-sm">How it works</CardTitle>
						</CardHeader>
						<CardContent className="space-y-3 p-5 text-xs text-muted-foreground">
							<p>
								<Check className="mr-2 inline size-3.5 text-primary" />
								Each subject receives one focused session.
							</p>
							<p>
								<Check className="mr-2 inline size-3.5 text-primary" />
								Sessions are scheduled on the next available evenings.
							</p>
							<p>
								<Check className="mr-2 inline size-3.5 text-primary" />
								Review or adjust them from Sessions.
							</p>
						</CardContent>
					</Card>
				</div>
			</div>
		</div>
	);
}
